#pragma once
typedef enum kErrors {
	SUCCESS = 0,
	INC_ARGS,
	ERR_OVERFLOW,
	MEM_ALLOC_ERR,
	INC_NUM_OF_ARGS,
	INC_FLAG,
	INC_FILE,
	INC_INP_DATA,
	INC_COMMENTS,
	UNKNOWN_FUNC,
	NO_POINT_COMMA,
	EXTRA_CHARACTERS,
	INC_SYNTAX,
	INC_DIV
} kErrors;
kErrors ProccessError(kErrors error);